name: Disconnected Readiness
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    uses: opendatahub-io/disconnected-readiness-scorer/.github/workflows/disconnected-readiness-check.yml@f8ec39b25663c6e705e3bc19b893c924d691477f
    with:
      rules: ""
